name: Update status ReadMe

on:
  push:
    branches: main

permissions:
    contents: write

jobs:
  update-status-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Run Progress Script
        run: python ./utils/update_status.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs(status): auto-update done status in README.md"
          file_pattern: 'README.md'
